on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Build package
        run: echo ${{ inputs.function-name }}