on:
  push:
    branches:
      - develop
    paths:
      - 'cmd/**/**.go'

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            clear_ratio:
              - 'cmd/daily/clear_ratio/**'
            active_users:
              - 'cmd/daily/active_users/**'

  clear-ratio:
    needs: changes
    timeout-minutes: 5
    if: ${{ needs.changes.outputs.clear_ratio == 'true' }}
    uses: './.github/workflows/deploy.yml'
    with:
      function-name: 'clear_ratio'

  active-users:
    needs: changes
    timeout-minutes: 5
    if: ${{ needs.changes.outputs.active_users == 'true' }}
    uses: './.github/workflows/deploy.yml'
    with:
      function-name: 'active_users'